### Data structure

#### List->elements are separated by comma and enclosed with square bracket
#### Heterogenous
#### List can be retrived using index
#### mutable

In [1]:
sample_list=[1,13.6,"hii",12,1]
sample_list

[1, 13.6, 'hii', 12, 1]

In [2]:
sample_list[0]

1

In [3]:
sample_list[10]

IndexError: list index out of range

In [5]:
sample_list[-2]

12

In [6]:
sample_list[0]=100

In [7]:
sample_list

[100, 13.6, 'hii', 12, 1]

### Tuple

#### Heterogenous
#### Parathensis
#### can retrive data using index
#### Immutable

In [10]:
sample_tuple=(1,13.6,"hi",12,1)
sample_tuple

(1, 13.6, 'hi', 12, 1)

In [11]:
sample_tuple[0]

1

In [14]:
sample_tuple[3]

12

In [13]:
sample_tuple[0]=100

TypeError: 'tuple' object does not support item assignment

### set

#### Does not allow duplicate
#### ordered-first place
#### In set,elements cannot be retrived using index
#### set is mutable

In [19]:
sample_set={1,13.6,"hi",12,1,127,25,25,"apple","king","ball"}
sample_set

{1, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [20]:
sample_set[-5]

TypeError: 'set' object is not subscriptable

In [33]:
sample_set[0]="hello"

TypeError: 'set' object does not support item assignment

In [35]:
sample_set.add(1000)

In [36]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [37]:
sample_set.remove("hi")

In [38]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'king'}

### Dictionary

##### Has key-value pair data structure
##### ket is unique
##### values can be duplicated
##### value can be retrived using key
##### key cannot be retrived using index

In [21]:
sample_dict={1:"apple",2:35.4,3:"data",6:35.4,7:35.4}
sample_dict

{1: 'apple', 2: 35.4, 3: 'data', 6: 35.4, 7: 35.4}

In [22]:
sample_dict[3]

'data'

In [24]:
sample_dict[4]

KeyError: 4

In [25]:
sample_dict[7]

35.4

In [26]:
sample_dict["apple"]

KeyError: 'apple'

In [27]:
sample_dict[7]=100

In [28]:
sample_dict

{1: 'apple', 2: 35.4, 3: 'data', 6: 35.4, 7: 100}

In [30]:
sample_dict[10]="Bussiness"

In [31]:
sample_dict

{1: 'apple', 2: 35.4, 3: 'data', 6: 35.4, 7: 100, 10: 'Bussiness'}

### Numpy: Package for Multidimensional array

In [40]:
import numpy as np

In [44]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [43]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [47]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [49]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [61]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [62]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [64]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [65]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])